name: Status Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint_build_and_test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint ngx-autosize-input
      - name: Build ngx-autosize-input
        run: npm run build ngx-autosize-input
      - name: Run Unit Tests
        run: npm run test ngx-autosize-input --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: joshuawwright/ngx-autosize-input
